language: python
install:
- pip install sphinx sphinx_rtd_theme mock
script:
- sphinx-build -W docs/source docs/html

deploy:
 provider: pages
 skip_cleanup: true
 keep-history: false
 github_token: $GH_TOKEN
 local_dir: docs/html
 on:
   branch: master

before_deploy:
- "echo 'ready?'"
- gem install fpm
- ./scripts/build_deb.sh

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file: python-qtpyvcp_*.deb
  skip_cleanup: true
  on:
    tags: true

# notifications:
#   irc:
#     channels:
#       - "chat.freenode.net#hazzy"
#     template:
#       - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
#       - "Diff view : %{compare_url}"
#       - "Build details : %{build_url}"
#
#   webhooks:
#     urls:
#       - https://webhooks.gitter.im/e/f52c254eacf15cb158b5
#     on_success: always
#     on_failure: always
#     on_start: never
