language: python
python: "2.7"

install:
- pip install sphinx sphinx_rtd_theme sphinx-notfound-page mock
- pip install git+https://github.com/KurtJacobson/sphinx-gitstamp@MoreInfo
- pip install --upgrade setuptools
- sudo apt-get install pyqt5-dev-tools

script:
- sphinx-build -Wv docs/source docs/html

deploy:
# publish docs on push
- provider: pages
  skip_cleanup: true
  keep-history: false
  github_token: $GH_TOKEN
  local_dir: docs/html
  on:
    branch: master

# publish docs on new release
- provider: pages
  skip_cleanup: true
  keep-history: false
  github_token: $GH_TOKEN
  local_dir: docs/html
  on:
    tags: true

# publish release to GitHub
- provider: script
  script: bash .travis/do_release.sh
  skip_cleanup: true
  on:
    tags: true

notifications:
  irc:
    channels:
      - "chat.freenode.net#hazzy"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
      - "Diff view : %{compare_url}"
      - "Build details : %{build_url}"

    on_success: change
    on_failure: always
