# Site information
site_name: QtPyVCP
site_author: Kurt Jacobson
site_description: Documentation for QtPyVCP, a PyQt5 based VCP toolkit for LinuxCNC
site_url: https://kcjengr.github.io/qtpyvcp/

# Copyright
copyright: Copyright &copy; 2017 - 2018 Kurt Jacobson

# Repository
repo_name: kcjengr/qtpyvcp
repo_url: https://github.com/kcjengr/qtpyvcp/
edit_uri: ""

# Configuration
theme:
  name: readthedocs

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.codehilite:
      guess_lang: true
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
- Home: index.md
- Dependencies: dependencies.md
- Installing: installing.md
- Tools:
  - QCompile: tools/qcompile.md
- Widgets:
  - Button Widgets:
    - SubCall Button: widgets/buttons/subcall_button.md
    - MDI Button: widgets/buttons/mdi_button.md
